services:
  mcp-server-hc3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server-hc3
    restart: unless-stopped
    ports:
      - "${MCP_HTTP_PORT:-3000}:3000"
    environment:
      # MCP Server Configuration
      - MCP_HTTP_HOST=0.0.0.0
      - MCP_HTTP_PORT=${MCP_HTTP_PORT:-3000}
      - MCP_TRANSPORT_TYPE=${MCP_TRANSPORT_TYPE:-http}

      # HC3 Configuration (Required)
      - HC3_HOST=${HC3_HOST}
      - HC3_USERNAME=${HC3_USERNAME}
      - HC3_PASSWORD=${HC3_PASSWORD}
      - HC3_PORT=${HC3_PORT:-80}

      # Server Configuration
      - SERVER_TIMEOUT=${SERVER_TIMEOUT:-10000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - mcp-hc3-network
    volumes:
      # Optional: Mount logs directory for persistence
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mcp-hc3-network:
    driver: bridge
    name: mcp-hc3-network

volumes:
  logs:
    driver: local
